<?php

/**
 * @file
 * Primary module hooks for Test Interface transaltion module.
 */

/**
 * Implements hook_theme().
 */
function tit_theme($existing, $type, $theme, $path) {
  return [
    'tit_page' => [
        'variables' => [
            'title' => NULL,
        ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function tit_preprocess_page(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'tit.page') {
    $variables['#attached']['library'][] = 'tit/global-scripts';
  }
}